version: '3'

services:

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code
    working_dir: /code/

  db:
<<<<<<< HEAD
    image: postgres:11
=======
    image: postgres:9.6
>>>>>>> origin
    networks:
      - bcros
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bcros
<<<<<<< HEAD
=======
    environment:
      - POSTGRES_PASSWORD=password
>>>>>>> origin

  search_api:
    image: search_api
    build:
      context: search-api
    volumes:
      - ./search-api:/opt/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/opt/app/src
    networks:
      - bcros

networks:
  bcros:
    driver: "bridge"

volumes:
  postgres-data:
